apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marshal-ingress
  namespace: marshal
spec:
  defaultBackend:
    service:
      name: caddy-ingress-svc
      port:
        number: 80
